---
# =============================================================================
# DynaKube Custom Resource
# =============================================================================
# Configures Dynatrace OneAgent and ActiveGate deployment
# Update the apiUrl with your Dynatrace environment URL
# =============================================================================
apiVersion: dynatrace.com/v1beta2
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  # Your Dynatrace environment URL
  # Format: https://{your-environment-id}.live.dynatrace.com/api
  apiUrl: https://ENVIRONMENT_ID.live.dynatrace.com/api

  # Reference to the secret containing API and PaaS tokens
  tokens: dynakube

  # OneAgent configuration - monitors all nodes
  oneAgent:
    # Cloud-native full stack injection (recommended for OpenShift)
    cloudNativeFullStack:
      # Tolerations to run on all nodes including master/infra
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists

      # Resource limits for OneAgent
      oneAgentResources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi

  # ActiveGate configuration - for routing and Kubernetes API monitoring
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api

    # Resource limits for ActiveGate
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi

    # Replicas for high availability
    replicas: 1

  # Skip SSL certificate validation (use only for self-signed certs)
  skipCertCheck: false

  # Network zone (optional)
  # networkZone: your-network-zone

  # Proxy configuration (if needed)
  # proxy:
  #   value: http://proxy.example.com:8080
