---
# =============================================================================
# Dynatrace API Tokens Secret
# =============================================================================
# Replace the token values with your actual Dynatrace tokens
#
# To create tokens in Dynatrace:
# 1. Go to Settings > Integration > Dynatrace API
# 2. Generate API Token with scopes:
#    - DataExport, entities.read, settings.read, activeGates.read,
#      DataExport, DataImport, LogExport, ReadConfig, WriteConfig
# 3. Generate PaaS Token (or use Operator token with installer download scope)
#
# Then apply: oc apply -f secret.yml
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: dynakube
  namespace: dynatrace
type: Opaque
stringData:
  # API Token - for Dynatrace API access
  apiToken: "dt0c01.XXXXXXXX.YYYYYYYY"

  # Data Ingest Token - for sending data to Dynatrace
  dataIngestToken: "dt0c01.XXXXXXXX.ZZZZZZZZ"
