---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dynatrace-operator
  namespace: dynatrace
spec:
  channel: stable
  installPlanApproval: Automatic
  name: dynatrace-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
